INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('RSR', '水库', 'WRP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('HMS', '水文测站', 'WRP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('LEV', '堤防（段）', 'WRP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('CLV', '海堤', 'WRP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('FWD', '蓄滞（行）洪区', 'WRP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('LAK', '湖泊', 'WRP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('PLD', '圩垸', 'WRP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('IDS', '机电排灌站', 'WRP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('SLU', '水闸', 'WRP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('RCS', '河道断面', 'WRP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('RCP', '跨河工程', 'WRP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('RTP', '治河工程', 'WRP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('LCS', '穿堤建筑物', 'WRP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('IRA', '灌区', 'WRP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('HPP', '水利发电工程', 'WRP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('SWC', '水土保持工程', 'WRP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('DIS', '字典', 'WRP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('1', '在建', 'PRST', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('2', '已建', 'PRST', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('9', '其他', 'PRST', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('FA', '长江上游干流区间', 'CTCD', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('FB', '长江中下游干流区间', 'CTCD', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('FC', '雅砻江流域', 'CTCD', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('FD', '岷江流域', 'CTCD', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('FE', '嘉陵江流域', 'CTCD', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('FF', '乌江流域', 'CTCD', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('FG', '洞庭湖水系', 'CTCD', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('FH', '汉江流域', 'CTCD', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('FJ', '鄱阳湖水系', 'CTCD', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('FK', '太湖流域', 'CTCD', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('1', '独流入海河流', 'RVTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('2', '国际河流', 'RVTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('3', '内陆河流', 'RVTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('4', '运河', 'RVTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('9', '其他', 'RVTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('01', '1985国家高程基准', 'DTPL', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('02', '1956黄海高程基准', 'DTPL', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('03', '波罗的海高程基准', 'DTPL', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('04', '广州高程基面', 'DTPL', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('05', '珠江高程基面', 'DTPL', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('06', '大连零点', 'DTPL', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('07', '废黄河零点', 'DTPL', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('08', '坎门零点', 'DTPL', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('09', '吴淞（口）高程基面', 'DTPL', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('10', '其他绝对基面', 'DTPL', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('11', '假定基面', 'DTPL', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('12', '测站基面', 'DTPL', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('13', '冻结基面', 'DTPL', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('1', '大（1）型', 'PRSC', 'RSR', 1, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('2', '大（2）型', 'PRSC', 'RSR', 2, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('3', '中型', 'PRSC', 'RSR', 3, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('4', '小（1）型', 'PRSC', 'RSR', 4, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('5', '小（2）型', 'PRSC', 'RSR', 5, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('1', 'I', 'PRGR', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('2', 'II', 'PRGR', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('3', 'III', 'PRGR', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('4', 'IV', 'PRGR', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('5', 'V', 'PRGR', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('1', '1', 'MNBLGR', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('2', '2', 'MNBLGR', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('3', '3', 'MNBLGR', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('4', '4', 'MNBLGR', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('5', '5', 'MNBLGR', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('1', '水利', 'BLSYS', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('2', '能源', 'BLSYS', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('3', '交通', 'BLSYS', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('4', '农业', 'BLSYS', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('5', '建设', 'BLSYS', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('6', '国企', 'BLSYS', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('9', '其他', 'BLSYS', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('1', '<0.05g', 'EQMTPKACLT', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('2', '0.05g', 'EQMTPKACLT', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('3', '0.10g', 'EQMTPKACLT', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('4', '0.15g', 'EQMTPKACLT', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('5', '0.20g', 'EQMTPKACLT', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('6', '0.30g', 'EQMTPKACLT', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('7', '≥0.4g', 'EQMTPKACLT', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('5', '<VI', 'BSSSIN', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('6', 'VI', 'BSSSIN', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('7', 'VII', 'BSSSIN', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('8', 'VIII', 'BSSSIN', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('9', '≥IX', 'BSSSIN', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('0', '未设防', 'FREQIN', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('6', 'VI', 'FREQIN', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('7', 'VII', 'FREQIN', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('8', 'VIII', 'FREQIN', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('9', '≥IX', 'FREQIN', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('01', '防洪', 'RSFN', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('02', '灌溉', 'RSFN', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('03', '供水', 'RSFN', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('04', '发电', 'RSFN', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('05', '养殖', 'RSFN', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('06', '航运', 'RSFN', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('07', '环境', 'RSFN', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('08', '旅游', 'RSFN', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('09', '调沙', 'RSFN', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('10', '防凌', 'RSFN', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('99', '其他', 'RSFN', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('1', '多年调节', 'RSRRGTPFM', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('2', '年调节', 'RSRRGTPFM', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('3', '不完全年调节', 'RSRRGTPFM', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('4', '径流式调节', 'RSRRGTPFM', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('9', '其他', 'RSRRGTPFM', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('01', '均质土坝', 'DMTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('02', '黏土心墙坝', 'DMTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('03', '黏土斜墙坝', 'DMTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('04', '混合型土坝', 'DMTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('05', '混凝土面板堆石坝', 'DMTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('06', '沥青面板堆石坝', 'DMTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('07', '沥青心墙堆石坝', 'DMTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('08', '混凝土重力坝', 'DMTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('09', '混凝土拱坝', 'DMTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('10', '混凝土连拱坝', 'DMTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('11', '混凝土支墩坝', 'DMTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('12', '浆砌石重力坝', 'DMTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('13', '浆砌石拱坝', 'DMTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('99', '其他', 'DMTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('1', '黏土防渗体', 'ASELST', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('2', '混凝土防渗墙', 'ASELST', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('3', '灌浆帷幕', 'ASELST', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('4', '混凝土面板', 'ASELST', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('5', '沥青混凝土', 'ASELST', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('6', '土工膜', 'ASELST', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('7', '综合型防渗体', 'ASELST', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('9', '其他', 'ASELST', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('1', '截水槽', 'BSASMS', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('2', '黏土铺盖', 'BSASMS', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('3', '混凝土防渗墙', 'BSASMS', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('4', '板桩', 'BSASMS', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('5', '灌浆帷幕', 'BSASMS', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('9', '其他', 'BSASMS', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('1', '坝体内排水', 'DRELST', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('2', '棱体排水', 'DRELST', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('3', '贴坡式排水', 'DRELST', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('4', '坝基排水', 'DRELST', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('5', '综合型排水', 'DRELST', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('0', '未设置排水体', 'DRELST', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('1', '卷扬式启闭机', 'HSDV', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('2', '螺杆式启闭机', 'HSDV', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('3', '液压式启闭机', 'HSDV', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('4', '无启闭设备', 'HSDV', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('9', '其他', 'HSDV', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('1', '混凝土有压洞', 'STST', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('2', '混凝土无压洞', 'STST', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('3', '浆砌石有压洞', 'STST', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('4', '浆砌石无压洞', 'STST', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('5', '内衬钢板有压洞', 'STST', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('9', '其他', 'STST', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('1', '平板钢闸门', 'GTST', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('2', '弧形钢闸门', 'GTST', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('3', '钢筋混凝土闸门', 'GTST', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('4', '木闸门', 'GTST', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('5', '钢木结构叠梁门', 'GTST', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('6', '自动翻版闸门', 'GTST', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('7', '闸阀', 'GTST', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('8', '无闸门', 'GTST', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('9', '其他', 'GTST', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('1', '国家级水利风景区', 'WTPRGR', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('2', '省级水利风景区', 'WTPRGR', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('3', '非水利风景区', 'WTPRGR', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('9', '其他', 'WTPRGR', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('1', '甲级', 'DSUNQL', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('2', '乙级', 'DSUNQL', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('3', '丙级', 'DSUNQL', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('9', '其他', 'DSUNQL', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('1', '特技', 'CNUNQL', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('2', '一级', 'CNUNQL', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('3', '二级', 'CNUNQL', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('4', '三级', 'CNUNQL', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('9', '其他', 'CNUNQL', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('01', '分部工程验收', 'ACTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('02', '单位工程验收', 'ACTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('03', '合同工程完工验收', 'ACTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('04', '中间机组启动验收', 'ACTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('05', '工程导（截）流验收', 'ACTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('06', '工程下闸蓄水验收', 'ACTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('07', '水电站泵站首（末）台机组启动验收', 'ACTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('08', '部分工程投入使用验收', 'ACTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('09', '水土保持工程验收', 'ACTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('10', '环境保护工程验收', 'ACTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('11', '消防设施验收', 'ACTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('12', '征地补偿与移民安置验收', 'ACTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('13', '工程建设档案验收', 'ACTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('14', '其他专项验收', 'ACTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('15', '竣工技术预验收', 'ACTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('16', '竣工验收', 'ACTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('99', '其他验收', 'ACTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('1', '长江水利委员会', 'RVBSADOR', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('2', '黄河水利委员会', 'RVBSADOR', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('3', '淮河水利委员会', 'RVBSADOR', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('4', '海河水利委员会', 'RVBSADOR', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('5', '珠江水利委员会', 'RVBSADOR', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('6', '松辽水利委员会', 'RVBSADOR', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('7', '太湖流域管理局', 'RVBSADOR', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('9', '其他', 'RVBSADOR', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('1', '自动监测', 'HYMNMT', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('2', '自动+人工', 'HYMNMT', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('3', '人工监测', 'HYMNMT', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('4', '无监测设施', 'HYMNMT', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('9', '其他', 'HYMNMT', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('1', '已建', 'HYMNSYCNST', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('2', '在建', 'HYMNSYCNST', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('3', '拟建', 'HYMNSYCNST', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('4', '暂无计划', 'HYMNSYCNST', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('9', '其他', 'HYMNSYCNST', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('1', 'I类', 'RSWQCT', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('2', 'II类', 'RSWQCT', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('3', 'III类', 'RSWQCT', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('4', 'IV类', 'RSWQCT', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('5', 'V类', 'RSWQCT', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('1', '工业废水废渣', 'MBPLSR', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('2', '农业化肥农药', 'MBPLSR', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('3', '生活污水垃圾', 'MBPLSR', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('4', '多源综合污染', 'MBPLSR', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('5', '其他', 'MBPLSR', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('01', '表面垂直位移', 'ENMNIT', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('02', '表面水平位移', 'ENMNIT', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('03', '内部位移', 'ENMNIT', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('04', '接缝位移', 'ENMNIT', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('05', '渗流压力', 'ENMNIT', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('06', '渗流水位', 'ENMNIT', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('07', '渗流量', 'ENMNIT', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('08', '应力应变', 'ENMNIT', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('09', '地震', 'ENMNIT', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('10', '水力学', 'ENMNIT', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('11', '环境量', 'ENMNIT', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('99', '其他监测项目', 'ENMNIT', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('1', '符合要求', 'SFEVUNQL', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('2', '不符合要求', 'SFEVUNQL', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('9', '其他', 'SFEVUNQL', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('1', '部级', 'VLDPLV', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('2', '省级', 'VLDPLV', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('3', '市级', 'VLDPLV', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('4', '县级', 'VLDPLV', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('9', '其他', 'VLDPLV', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('1', '满足要求', 'FLSFAPSOP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('2', '基本满足要求', 'FLSFAPSOP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('3', '不满足要求', 'FLSFAPSOP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('9', '其他', 'FLSFAPSOP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('1', '满足要求', 'SSSFAPSOP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('2', '基本满足要求', 'SSSFAPSOP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('3', '不满足要求', 'SSSFAPSOP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('4', '按规范允许未复核', 'SSSFAPSOP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('9', '其他', 'SSSFAPSOP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('1', '功能变化', 'MNCS', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('2', '建设不当', 'MNCS', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('3', '需求萎缩', 'MNCS', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('4', '功能替代', 'MNCS', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('5', '病险严重', 'MNCS', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('6', '淤积严重', 'MNCS', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('7', '建设占用', 'MNCS', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('9', '其他', 'MNCS', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('1', '特别重大险情', 'DNSTGR', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('2', '重大险情', 'DNSTGR', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('3', '较大险情', 'DNSTGR', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('4', '一般险情', 'DNSTGR', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('9', '其他', 'DNSTGR', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('1', '水文站', 'STTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('2', '水位站', 'STTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('3', '降水量站', 'STTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('4', '水面蒸发站', 'STTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('5', '地下水战（井）', 'STTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('6', '水质站', 'STTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('7', '土壤墒情站', 'STTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('9', '其他', 'STTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('1', '土堤', 'LVTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('2', '石堤', 'LVTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('3', '混凝土堤', 'LVTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('4', '土堤加护砌堤', 'LVTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('5', '混合堤', 'LVTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('9', '其他', 'LVTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('1', '左岸', 'BNSD', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('2', '右岸', 'BNSD', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('1', '草皮', 'LNSDBNPTCN', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('2', '浆砌石', 'LNSDBNPTCN', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('3', '干砌石', 'LNSDBNPTCN', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('4', '混凝土', 'LNSDBNPTCN', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('5', '钢筋混凝土', 'LNSDBNPTCN', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('6', '无护坡', 'LNSDBNPTCN', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('9', '其他', 'LNSDBNPTCN', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('1', '防渗铺盖', 'LVBSASMS', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('2', '截水槽', 'LVBSASMS', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('3', '截水墙', 'LVBSASMS', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('4', '压渗盖重', 'LVBSASMS', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('5', '排水沟', 'LVBSASMS', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('6', '减压井', 'LVBSASMS', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('7', '填塘', 'LVBSASMS', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('9', '其他', 'LVBSASMS', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('1', '高速公路', 'LVCNRDGR', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('2', '一级公路', 'LVCNRDGR', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('3', '二级公路', 'LVCNRDGR', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('4', '三级公路', 'LVCNRDGR', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('5', '四级公路', 'LVCNRDGR', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('9', '其他', 'LVCNRDGR', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('01', '堤身沉降', 'LVENMNIT', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('02', '堤身水平位移', 'LVENMNIT', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('03', '水位', 'LVENMNIT', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('04', '潮位', 'LVENMNIT', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('05', '堤身浸润线', 'LVENMNIT', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('06', '近岸河床冲淤', 'LVENMNIT', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('07', '水流流态', 'LVENMNIT', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('08', '附属建筑物位移', 'LVENMNIT', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('09', '渗流压力', 'LVENMNIT', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('10', '减压排渗工程的渗控效果', 'LVENMNIT', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('11', '崩岸险工段土体崩坍情况', 'LVENMNIT', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('12', '冰情', 'LVENMNIT', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('13', '波浪', 'LVENMNIT', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('99', '其他', 'LVENMNIT', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('1', '1～2年一遇', 'ACOPFR', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('2', '3年一遇', 'ACOPFR', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('3', '3～5年一遇', 'ACOPFR', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('4', '5年一遇', 'ACOPFR', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('5', '5～10年一遇', 'ACOPFR', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('6', '10年一遇', 'ACOPFR', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('7', '10年一遇以上', 'ACOPFR', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('1', '淡水湖', 'HCCL', 'RSR', null, '湖水矿化度小于1g/L');

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('2', '微咸水湖', 'HCCL', 'RSR', null, '湖水矿化度为1～35g/L');

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('3', '咸水湖', 'HCCL', 'RSR', null, '湖水矿化度为35～50g/L');

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('4', '盐湖', 'HCCL', 'RSR', null, '湖水矿化度大于50g/L');

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('5', '干盐湖', 'HCCL', 'RSR', null, '地下有晶间卤水或固体盐矿，是重要的沉积矿床');

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('6', '湖水化学性质不明湖泊', 'HCCL', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('7', '时令湖', 'HCCL', 'RSR', null, '西部地区季节性蓄水的湖泊');

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('1', '大型机配排灌站', 'IDSTTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('2', '中型机配排灌站', 'IDSTTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('3', '小型机配排灌站', 'IDSTTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('4', '大型点配排灌站', 'IDSTTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('5', '中型点配排灌站', 'IDSTTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('6', '小型点配排灌站', 'IDSTTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('9', '其他', 'IDSTTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('1', '进水闸', 'SLTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('2', '退水闸', 'SLTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('3', '节制闸', 'SLTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('4', '挡潮闸', 'SLTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('5', '船闸', 'SLTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('9', '其他', 'SLTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('01', '防洪', 'SLFN', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('02', '泄洪', 'SLFN', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('03', '调洪', 'SLFN', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('04', '分洪', 'SLFN', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('05', '分凌', 'SLFN', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('06', '灌溉', 'SLFN', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('07', '蓄水', 'SLFN', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('08', '供水', 'SLFN', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('09', '航运', 'SLFN', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('10', '拦污', 'SLFN', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('99', '其他', 'SLFN', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('1', '一类闸', 'SLSFTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('2', '二类闸', 'SLSFTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('3', '三类闸', 'SLSFTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('4', '四类闸', 'SLSFTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('9', '其他', 'SLSFTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('1', '桥梁', 'RCPRTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('2', '渡槽', 'RCPRTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('3', '管道', 'RCPRTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('4', '倒虹吸', 'RCPRTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('5', '缆线', 'RCPRTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('6', '隧道', 'RCPRTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('9', '其他', 'RCPRTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('1', '护岸', 'RTPTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('2', '护滩', 'RTPTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('3', '丁坝', 'RTPTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('4', '裁弯', 'RTPTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('5', '堵汊', 'RTPTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('6', '倒流排', 'RTPTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('9', '其他', 'RTPTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('1', '水库', 'IRAHWPRTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('2', '塘坝', 'IRAHWPRTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('3', '泵站', 'IRAHWPRTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('4', '引水坝', 'IRAHWPRTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('5', '引水闸', 'IRAHWPRTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('6', '机井', 'IRAHWPRTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('9', '其他', 'IRAHWPRTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('1', '大（1）型水电站', 'PWPRTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('2', '大（2）型水电站', 'PWPRTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('3', '中型水电站', 'PWPRTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('4', '小（1）型水电站', 'PWPRTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('5', '小（2）型水电站', 'PWPRTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('9', '其他', 'PWPRTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('1', '国家水土保持重点工程小流域综合治理工程', 'SWCPRTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('2', '国家水土保持重点工程坡耕地水土综合整治工程', 'SWCPRTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('3', '国家水土保持重点工程淤地坝工程', 'SWCPRTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('4', '国家水土保持重点工程崩岗治理工程', 'SWCPRTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('9', '其他', 'SWCPRTP', 'RSR', null, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('SF', '渗流量', 'MNRITM', 'RSR', 4, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('RZ', '水位', 'MNRITM', 'RSR', 1, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('PP', '雨量', 'MNRITM', 'RSR', 2, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('VD', '视频', 'MNRITM', 'RSR', 7, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('PI', '图片', 'MNRITM', 'RSR', 8, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('DP', '位移', 'MNRITM', 'RSR', 5, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('DL', '位错', 'MNRITM', 'RSR', 10, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('TMW', '温度', 'MNRITM', 'RSR', 6, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('ICW', '倾斜', 'MNRITM', 'RSR', 9, NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('SP', '渗流压力', 'MNRITM', 'RSR', 3, NULL);
--渗流压力分几类:
INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('SPF', '坝基渗压', 'MNRITM', 'RSR', 11, NULL);
INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('SPB', '坝体渗压', 'MNRITM', 'RSR', 12, NULL);
INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('SPR', '基岩渗压', 'MNRITM', 'RSR', 13, NULL);
INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('SFB', '大坝渗流量', 'MNRITM', 'RSR', 14, NULL);
INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('SFP', '绕坝渗流量', 'MNRITM', 'RSR', 15, NULL);




INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('1', '一级建筑物', 'LVGR', 'RSR', '1', NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('2', '二级建筑物', 'LVGR', 'RSR', '2', NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('3', '三级建筑物', 'LVGR', 'RSR', '3', NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('4', '四级建筑物', 'LVGR', 'RSR', '4', NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('5', '五级建筑物', 'LVGR', 'RSR', '5', NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('1', '草皮', 'RVSDBNPTCN', 'RSR', '1', NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('2', '浆砌石', 'RVSDBNPTCN', 'RSR', '2', NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('3', '干砌石', 'RVSDBNPTCN', 'RSR', '3', NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('4', '混凝土', 'RVSDBNPTCN', 'RSR', '4', NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('5', '钢筋混凝土', 'RVSDBNPTCN', 'RSR', '5', NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('6', '无护坡', 'RVSDBNPTCN', 'RSR', '6', NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('9', '其它', 'RVSDBNPTCN', 'RSR', '7', NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('1', '截水槽', 'DMBSASMS', 'RSR', '1', NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('2', '粘土铺盖', 'DMBSASMS', 'RSR', '2', NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('3', '混凝土防渗墙', 'DMBSASMS', 'RSR', '3', NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('4', '板桩', 'DMBSASMS', 'RSR', '4', NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('5', '灌浆帷幕', 'DMBSASMS', 'RSR', '5', NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('9', '其他', 'DMBSASMS', 'RSR', '9', NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('1', '一类坝', 'DMSFCL', 'RSR', '1', NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('2', '二类坝', 'DMSFCL', 'RSR', '2', NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('3', '三类坝', 'DMSFCL', 'RSR', '3', NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('9', '其它', 'DMSFCL', 'RSR', '9', NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('1', '启动过', 'EXST', 'RSR', '1', NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('2', '演练过', 'EXST', 'RSR', '2', NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('3', '宣传过', 'EXST', 'RSR', '3', NULL);

INSERT INTO SWS_DATA_DICT (CD, NM, FLD, WRP, ORD, NOTE) VALUES ('9', '其他', 'EXST', 'RSR', '9', NULL);
